FROM python:3.11-slim
WORKDIR /app/tgbot

RUN pip3 install --no-cache-dir pytelegrambotapi requests python-dotenv || true

COPY tgbot ./

ENV PYTHONUNBUFFERED=1

CMD ["python3", "uni_eduplatform_bot.py"]
