version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: lisa
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  g4f:
    image: hlohaus789/g4f:latest
    restart: always
    shm_size: "2g"
    ports:
      - "8080:8080"
      - "1337:1337"
      - "7900:7900"

volumes:
  db_data: