# Generated by Django 4.2 on 2024-06-11 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Represents a database migration with its associated operations.

        This class encapsulates the steps needed to evolve a database schema,
        including dependencies on other migrations and the actual operations
        to be performed.

        Attributes:
            initial (bool): Indicates whether this is the initial migration.
            dependencies (list): A list of other Migration instances that must be applied before this one.
            operations (list): A list of database operation objects to perform during the migration.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analyticity", models.FloatField(null=True)),
                ("leadership", models.IntegerField(null=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
