# Generated by Django 5.0.4 on 2024-06-12 03:18

from django.db import migrations


class Migration(migrations.Migration):
    """
    A class representing a database migration.

        This class encapsulates the steps needed to update a database schema,
        including dependencies on other migrations and the actual operations
        to be performed.

        Attributes:
            dependencies: A list of other migrations that must be applied before this one.
            operations: A list of operations to perform during the migration.
    """

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentanalytics",
            old_name="student",
            new_name="student_id",
        ),
    ]
