version: '3.3'
volumes:
  static:
name: compose-prod

services:
  client:
    image: ishutachkaa/frontend:PROD
    volumes:
      - static:/client/build/
  
  api: &api
    image: ishutachkaa/backend-subjects:PROD
    env_file:
      - ./env/.env.subjects
    command: ./cmd.subjects.sh
    volumes:
      - ../dbs/subjects_db.sqlite3:/app/db.sqlite3
      - ./backups/subjects_db_backup.json:/app/courses/fixtures/subjects_db_backup.json
      - ./startscripts/cmd.subjects.sh:/app/cmd.subjects.sh
      - static:/app/static/
    restart: unless-stopped
    depends_on:
      - client

  users:
    image: ishutachkaa/backend-users:PROD
    env_file:
      - ./env/.env.users
    command: ./cmd.users.sh
    volumes:
      - ../dbs/users_db.sqlite3:/app/db.sqlite3
      - ./backups/users_db_backup.json:/app/users/fixtures/users_db_backup.json
      - ./startscripts/cmd.users.sh:/app/cmd.users.sh
      - static:/app/static/
    depends_on:
      - client
    restart: unless-stopped

  tests:
    image: ishutachkaa/backend-tests:PROD
    env_file:
      - ./env/.env.tests
    command: ./cmd.tests.sh
    volumes:
      - ../dbs/tests_db.sqlite3:/app/db.sqlite3
      - ./backups/tests_db_backup.json:/app/tests/fixtures/tests_db_backup.json
      - ./startscripts/cmd.tests.sh:/app/cmd.tests.sh
      - static:/app/static/
    depends_on:
      - client
    restart: unless-stopped

  gateway:
    image: nginx
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
    restart: unless-stopped
    depends_on:
      - client
      - users
      - tests
      - api