version: "3.3"
volumes:
  static:
services:
  client:
    build:
      context: ../
      dockerfile: client/Dockerfile
    volumes:
      - static:/client/build/

  api: &api
    build:
      context: ../subjects
      dockerfile: docker/dev/Dockerfile
    env_file:
      - ./env/.env.subjects
    command: sh /app/cmd.subjects.sh
    volumes:
      - ../dbs/subjects_db.sqlite3:/app/db.sqlite3
      - ./backups/subjects_db_backup.json:/app/courses/fixtures/subjects_db_backup.json
      - ./startscripts/cmd.subjects.sh:/app/cmd.subjects.sh
      - static:/app/static/
    restart: unless-stopped
    depends_on:
      - client

  users:
    build: ../users/
    env_file:
      - ./env/.env.users
    command: sh /app/cmd.users.sh
    volumes:
      - ../dbs/users_db.sqlite3:/app/db.sqlite3
      - ./backups/users_db_backup.json:/app/users/fixtures/users_db_backup.json
      - ./startscripts/cmd.users.sh:/app/cmd.users.sh
      - static:/app/static/
    depends_on:
      - client
    restart: unless-stopped

  tests:
    build: ../tests/
    env_file:
      - ./env/.env.tests
    command: sh /app/cmd.tests.sh
    volumes:
      - ../dbs/tests_db.sqlite3:/app/db.sqlite3
      - ./backups/tests_db_backup.json:/app/fixtures/tests_db_backup.json
      - ./startscripts/cmd.tests.sh:/app/cmd.tests.sh
      - static:/app/static/
    depends_on:
      - client
    restart: unless-stopped

  # analytics:
  #   build: ../analytics/
  #   env_file:
  #     - ./env/.env.analytics
  #   command: ./cmd.analytics.sh
  #   volumes:
  #     - ../dbs/analytics_db.sqlite3:/app/db.sqlite3
  #     - ./startscripts/cmd.analytics.sh:/app/cmd.analytics.sh
  #     - static:/app/static/
  #     - ../tests/tests/models.py:/app/tests/models.py
  #     - ../dbs/tests_db.sqlite3:/app/tests/db.sqlite3
  #   depends_on:
  #     - client
  #     - tests
  #   restart: unless-stopped

  gateway:
    image: nginx
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/

    restart: unless-stopped
    depends_on:
      - client
      - users
      - tests
      - api
      # - analytics
