# Generated by Django 4.2 on 2024-02-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_grade_delete_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('id_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testuser')),
            ],
        ),
    ]
