# Generated by Django 4.2 on 2025-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_result_score_alter_result_points_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='user_answer',
            field=models.IntegerField(),
        ),
    ]
