# Generated by Django 4.2 on 2024-06-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(help_text='Unique identifier of the student.', unique=True)),
                ('analyticity', models.IntegerField(default=0, help_text='Analyticity score of the student.')),
                ('leadership', models.IntegerField(default=0, help_text='Leadership score of the student.')),
            ],
            options={
                'verbose_name_plural': 'Student Analytics',
            },
        ),
    ]
