# Generated by Django 4.2 on 2024-06-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_studentanalyticstest_studentanalyticstheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanalyticstest',
            name='analyticity_test',
            field=models.IntegerField(default=0, help_text='Analyticity score of the student.'),
        ),
        migrations.AlterField(
            model_name='studentanalyticstheme',
            name='analyticity_theme',
            field=models.IntegerField(default=0),
        ),
    ]
