# Generated by Django 4.2 on 2024-06-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_studentanalyticstest_analyticity_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanalyticstest',
            old_name='test_id',
            new_name='test',
        ),
    ]
