# Generated by Django 4.2 on 2024-06-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_studentleadershiptheme_studentleadershiptest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleadershiptest',
            name='leadership_test',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentleadershiptheme',
            name='leadership_theme',
            field=models.IntegerField(default=0),
        ),
    ]
