# Generated by Django 4.2 on 2025-03-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_studentleadershiptest_leadership_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnalyticsCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(help_text='Identifier of the student.')),
                ('subject_id', models.IntegerField()),
                ('analyticity_course', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Student Analytics for Course',
            },
        ),
        migrations.CreateModel(
            name='StudentLeadershipCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(help_text='Identifier of the student.')),
                ('subject_id', models.IntegerField()),
                ('leadership_course', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Student Leadership for Course',
            },
        ),
    ]
