name: CI/CD Pipeline test

on:
  push:
    branches: [ "practika-develop" ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Тестики ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies for tests
        working-directory: ./tests
        run: pip install -r requirements.txt

      - name: Run Django Tests
        working-directory: ./tests
        run: python manage.py test
      # ------------------------------

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./tests
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/eduplatform:latest


  deploy:
    needs: build-and-validate
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.SSH_PASSPHRASE }} 
          
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/eduplatform:latest
            
            docker stop practice-app || true
            docker rm practice-app || true
            
            docker run -d \
              --name practice-app \
              -p 7070:7000 \
              -e DEBUG='True' \
              -e SECRET_KEY='django-practice-key' \
              -e ALLOWED_HOSTS='*' \
              -e CSRF_TRUSTED_ORIGINS='http://${{ secrets.HOST }}:7070' \
              ${{ secrets.DOCKER_USERNAME }}/eduplatform:latest